POST http://localhost:3000/scrape
Content-Type: application/json

{
    "url": "https://en.wikipedia.org/wiki/Luis_Mu%C3%B1oz_Mar%C3%ADn_International_Airport"
}

### Retrieve Data by URL
GET http://localhost:3000/data?url=https://en.wikipedia.org/wiki/Luis_Mu%C3%B1oz_Mar%C3%ADn_International_Airport